name: CI/CD Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "src/backend/**"

env:
  ACR_NAME: acr300622210  # Nom de ton Azure Container Registry
  IMAGE_NAME: baqtestappbackend  # Nom de l'image Docker
  RESOURCE_GROUP: 109-300221-quentin  # Groupe de ressources Azure
  CONTAINER_APP_NAME: baqtestappbackend  # Nom de l'Azure App Container

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connexion à Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Construire et pousser l'image Docker
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest ./src/backend
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Mettre à jour l'Azure App Container
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
